### ISSUE TITLE
A few translations still missing

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Future#1050]
Action Workflows screen:
![Screenshot 2024-11-21 at 3 00 24 PM](https://github.com/user-attachments/assets/8beda52f-3152-4f07-95be-a35ce375e43b)

**Comment by andergmartins** [comment]
For the first screenshot, that only happens if you install the plugin for the first time in English, and then move to Spanish. It will not edit the post title that was already created in English.

Here is the result if you install the plugin directly on a Spanish site:

![image](https://github.com/user-attachments/assets/b275aacd-064f-45e5-9730-bf8111749ec6)

**Comment by stevejburge** [comment]
@andergmartins Yes, that's true. There's no solution for that probably
