### ISSUE TITLE
Update plugin author name

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Future#125]
should be "PublishPress"
<img width="667" alt="pe-author" src="https://user-images.githubusercontent.com/3868028/133666030-6be091cf-56d2-4947-b74b-efef5c0e5597.png">

**Comment by contactashish13** [comment]
@stevejburge I'm not sure this can be changed from the code. That said, I have added my name to the contributors list as part of this PR :)

**Comment by stevejburge** [comment]
@contactashish13 It's done by changing the author name in the comments of post-expirator.php

**Comment by contactashish13** [comment]
@stevejburge I don't think [that's the place](https://github.com/publishpress/PublishPress-Future/blob/main/post-expirator.php#L6)

**Comment by stevejburge** [comment]
I'm 99% sure it is. I updated it in my commit https://github.com/publishpress/PublishPress-Future/commit/c7367d75d5e3d77745c0b3b8d8da527091a17f13

**Comment by contactashish13** [comment]
@stevejburge your commit is from 11 days ago but my reference [here](https://github.com/publishpress/PublishPress-Future/issues/125#issuecomment-922890020) was from the master branch. Looks like your changes are already part of the master and that's why I could't find any reference to the old author.
