### ISSUE TITLE
Combining Multiple Cron Events

### ISSUE THREAD

**Issue by madanpraba** [publishpress/PublishPress-Future#149]
A site like job management, Event management has many more corn events to execute based on the event expiration date. In most cases, there are many posts having the same time to expire. In this situation, there were a lot of corn events for the same functions with different arguments (post id) which consume a lot of server resources. 

To overcome this, adding the corn event to the existing same cron event will combine all the arguments in an array. for example, corn event 1 [post id 1], cron event 2 [post id 2] are the normal functions. if we combine together it will look like corn event 1 [post id 1, post id 2]. So one cron event is enough.

**Comment by andergmartins** [comment]
We should implement this creating a dedicated queue for post expirations. But it should be built and named in a way we could pack it in a shared library and reuse it on the other plugins, keeping in mind we have plans to centralize or integrate our plugins. Expiration is not the only event/task that would be enqueued there (#334).

**Comment by andergmartins** [comment]
Note for self: Maybe worths using https://actionscheduler.org/

**Comment by andergmartins** [comment]
Thanks @madanpraba we are taking the path to use the action scheduler library from WooCommerce. This will make it have only one cron job for triggering the queue, and the queue will be shared among other 3rd plugins, instead of create our own queue that would run concurrently. Having a lot of posts in the same cron hook execution could lead to timeout issues, if too many posts are expiring together. Having a queue makes it more reliable and traceable.
