### ISSUE TITLE
"Expiration Taxonomies" Terminology can be clearer

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Future#294]
Should we include the taxonomy name, rather than saying "Expiration Taxonomies (Taxonomy)"

![Screen Shot 2022-10-17 at 1 15 34 PM](https://user-images.githubusercontent.com/3868028/196241463-7afce2cd-618e-4d15-bdfa-99fe83ebaecf.png)

The Classic Editor version does show the taxonomy name:
![Screen Shot 2022-10-17 at 1 17 26 PM](https://user-images.githubusercontent.com/3868028/196241722-59eb5be5-9b94-4aa4-a65a-1b48ef35c7e4.png)

**Comment by andergmartins** [comment]
The taxonomies options in the "How to expire" field could be renamed to indicate an action:

* Replace <taxonomy> term(s)
* Add <taxonomy> term(s)
* Remove <taxonomy> term(s)

**Comment by andergmartins** [comment]
@stevejburge Do you think these labels make sense and are clear enough? I'm trying to make it shorter since some taxonomy names can be long, for example:

![image](https://github.com/publishpress/PublishPress-Future/assets/407131/48459ab7-0ca3-4e38-b10a-affece84c374)

For tags, it would be:

* "Keep all current tags and add new tags" becomes "Append tags"
* "Remove all current tags and add new tags" becomes "Replace all tags"
* "Remove selected tags" stay as it is

**Comment by stevejburge** [comment]
@andergmartins OK, I'm open to that.

Instead of "Append tags" we could try "Add extra tags"
