### ISSUE TITLE
Decide what to do with Post Publish time

### ISSUE THREAD

**Issue by rizaardiyanto1412** [publishpress/PublishPress-Future#310]
It's not quite clear the functionality of post/page publish time
![image](https://user-images.githubusercontent.com/83811723/201934355-189ea6bc-2ee2-496c-93c6-d9dab17e599f.png)

We should decide whether we:
1. Keep this functionality, but add more details on the use case
2. Remove it

**Comment by andergmartins** [comment]
@stevejburge @rizaardiyanto1412 I'm not sure about a real use case for that option.

The only reason I can think now for using that option is that the admin could decide to use publish time as the default value for the post expiration so that date can be manually updated to some another date close, by convenience. 

Not sure that example is clear enough, but maybe that shows the option probably do not have a real usage.

A suggestion to improve it is to remove that option, and add radio buttons in the Custom option params (if selected) to select the base date to consider when calculating the default expiration date. Right now it uses the current date time only, but we can give the option to calculate the custom date range based on the publish date as well, and not only the current date when the post is being edited. Something like:

![Screenshot 2022-12-15 at 19 30 37](https://user-images.githubusercontent.com/407131/207981051-967e12da-7ed5-4ca4-9a89-60cb2543d296.png)

**Comment by stevejburge** [comment]
@andergmartins @rizaardiyanto1412 I think we can safely remove that "Post/Page Publish Time" option.

We can also improve the label. "Default Date/Time Duration" is unclear.

Would this be clearer? "Expiration Date and Time"

**Comment by andergmartins** [comment]
The Publish Time was removed on #325, but the label still can be improved.
@stevejburge what about "Default date/time offset"?

**Comment by stevejburge** [comment]
@andergmartins Yes, your suggestion is better than mine
