### ISSUE TITLE
No language packages for Pro

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Future#426]
@andergmartins I'm talking with @wocmultimedia and realize there's no language file for the Pro plugins yet

**Comment by wocmultimedia** [comment]
I downloaded the zip pot. Can I use it to make the ES-FR-IT translations?
Please, give me confirmation, so I start translating.
Thanks
Angelo

**Comment by wocmultimedia** [comment]
@andergmartins @stevejburge 
Hello,
I found out that besides woocommerce and Action Scheduler missing there's another bug in the reference path for instance the code for this string 
![image](https://github.com/publishpress/PublishPress-Future/assets/2352240/35f85c2e-bddc-4d0a-a191-8d5ead4c80f1)
 point at something including publishpress-future/src....
but inside the folder there's no such publishpress-future/src... but post-expirator/src... and opening this file with notepad I found the string reference. Please have a look at shots below
![image](https://github.com/publishpress/PublishPress-Future/assets/2352240/494fb701-089c-490f-b974-33629b30089b)
![image](https://github.com/publishpress/PublishPress-Future/assets/2352240/8bbddea3-f9b5-4dfc-9664-0981795e1106)
![image](https://github.com/publishpress/PublishPress-Future/assets/2352240/cf2510d5-34af-4727-b22c-5ac7f2890dd0)

**Comment by wocmultimedia** [comment]
Hi @andergmartins @stevejburge 
I have made the Italian translation of Future PRO, here's a copy of the files to add to the plugin languages folder.
Spanish and French coming soon
[PublishPress-Future-PRO_ItalianTranslation_June2023.zip](https://github.com/publishpress/PublishPress-Future/files/11681022/PublishPress-Future-PRO_ItalianTranslation_June2023.zip)

**Comment by wocmultimedia** [comment]
@andergmartins @stevejburge 
Hi,
I need urgently to understand the meaning of these strings **Future Action** and **Future Action Complete "%s"**
I don't understand if Future in this case means in the future or related to the name of the plugin Future. Please, give me a quick reply because I'm stuck and no code reference is available.
Thanks
Angelo

**Comment by stevejburge** [comment]
Hi @wocmultimedia 

"Future" means both. It is the name of the plugin, and also it is about events that will happen in the future.

**Comment by wocmultimedia** [comment]
Hi,
This is ambiguos because If it means a specific action made only by Future plugin the I have to translate as it is Future otherwise if it means a common action made in the future time then it has to be translated different and accorded with language and singular/plural.
So let me understand. I enclose a shot
![shot_Future_word](https://github.com/publishpress/PublishPress-Future/assets/2352240/f88a4919-3df5-4776-8c76-60f019010156)
this translation is not totally proof till I don't understand it

**Comment by stevejburge** [comment]
@wocmultimedia OK, this makes sense in English bug maybe this doesn't translate so well.

Let's say that "Future" is the plugin name

**Comment by wocmultimedia** [comment]
I guessed well and I will correct it according to the word as saying "an action typical of Future plugin", isn't it?

**Comment by wocmultimedia** [comment]
I don't use these words but the meaning is that. For instance the string "Future Actions" in Spanish will be "Acción Future" with the F of Future in capital letter meaning that is belonging to the plugin otherwise it's a mistake because should be "Acción futura" with the meaning of an action made in the future. The same is for Italian and French. Likewise if it was "Elementor Action" it would be "Acción Elementor"

**Comment by stevejburge** [comment]
Thanks @wocmultimedia

**Comment by wocmultimedia** [comment]
I made the two translations Spanish and Italian. Below you find a zip file to add the files to the languages folder. 
When you will release the new version I will check if there's something not correct, so far I cannot make better than this because I have no code reference at all to Action Scheduler nor to Future Action.
[PublishPress-Future-PRO_IT-ES_Translations_June2023.zip](https://github.com/publishpress/PublishPress-Future/files/11691152/PublishPress-Future-PRO_IT-ES_Translations_June2023.zip)

**Comment by andergmartins** [comment]
Thanks @wocmultimedia I have fixed POT file and added the translations based on the files you sent. Thank you.
