### ISSUE TITLE
Email and Actions Log don't show post title and post type after post is deleted

### ISSUE THREAD

**Issue by rizaardiyanto1412** [publishpress/PublishPress-Future#507]
ISSUE in details:
Email expiration is empty on custom post type. Works fine on regular post type (Post/ Page)

Step to replicate:
1. Install: https://wordpress.org/plugins/custom-post-type-ui/
2. Create a new post type
3. Create a new post and set expiration to "Delete"
4. Observe issue, the email is empty

Original report: https://wordpress.org/support/topic/empty-email-error-v3-0-3-follow-on/
https://wordpress.org/support/topic/empty-email-error-v3-0-3/

PHP: 8.0
Future: 3.4

Normal:
![image](https://github.com/publishpress/PublishPress-Future/assets/83811723/8abb11a8-b050-4203-b5b6-2e9b00b51faf)

Issue:

![image](https://github.com/publishpress/PublishPress-Future/assets/83811723/ecfb8d1c-ed57-4da2-8d8b-33afea6ab787)

**Comment by andergmartins** [comment]
Thanks for the report, that is probably happening because the post is deleted before the email is sent. The title and other info will not be available anymore. I will see what we can do for fixing this.

**Comment by andergmartins** [comment]
This is related to the post register has been deleted from the DB before the email is sent. A similar issue you might see in the actions log. It will not show the post title and post type, because the post no longer exists. It doesn't happen to 'post' and 'page' because by default the post is trashed before being really deleted. The register on that case is still on the DB.
We will need to cache the post type, and post title in the action args, so that info can be used after the post is deleted.

**Comment by rizaardiyanto1412** [comment]
Original report: https://wordpress.org/support/topic/empty-post-link-with-custom-post-type-follow-on-2/

The post title show up, but not with post link

![image](https://github.com/publishpress/PublishPress-Future/assets/83811723/53daa90a-14af-4021-9b37-6375b2a4024a)
