### ISSUE TITLE
Remove specific term not working for Authors

### ISSUE THREAD

**Issue by rizaardiyanto1412** [publishpress/PublishPress-Future#550]
Step to replicate:
1. Setup on Future Action setting > Post type
2. "Remove selected term"
3. Login as author
4. Create new post
5. Publish
6. Observe issue, upon expiring, it does not run "remove selected term"

Video: https://www.loom.com/share/07c5b9f09d6f4ea0b100cc53868d4338

Original report: https://wordpress.org/support/topic/not-removing-category-after-expiry-it-seems-its-not-detecting-the-chosen-term/

**Comment by andergmartins** [comment]
I can also confirm the bug.
It happens when the author doesn't have permission to set expiration, but the default expiration settings is still used (but missing the term).

![image](https://github.com/publishpress/PublishPress-Future/assets/407131/6e4004f3-2875-46ce-92ab-7740d5f5626e)

Here is another test after adding permissions to Authors to expire posts:

![image](https://github.com/publishpress/PublishPress-Future/assets/407131/e39c6f57-048e-4c25-8226-8c60adc355f7)
