### ISSUE TITLE
Hide metabox from Media Library files

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Future#56]
We don't need the PE metabox for Media Library files:
<img width="838" alt="Screen Shot 2021-07-02 at 11 39 21 AM" src="https://user-images.githubusercontent.com/3868028/124298551-608e9b00-db2a-11eb-9fb9-1c30f9175dd8.png">

**Comment by contactashish13** [comment]
@stevejburge in PR https://github.com/publishpress/PublishPress-Future/pull/58 have added a filter so that users can unset more post types if they wish to. Defaults to `attachment`

```
	apply_filters( 'postexpirator_unset_post_types', array( 'attachment' ) );
```

Besides this have fixed a bit of a discrepancy which made no sense to me. The code was:
- using all post types for showing the meta box: [here](https://github.com/publishpress/PublishPress-Future/pull/58/files#diff-cbad8a0f4ee75b07aa33761be03e84f3d1196863f60e6fbe01f329c831f23211L342-L343)
- but using only `public` post types for showing the `Expires` column in the listing screen: [here](https://github.com/publishpress/PublishPress-Future/pull/58/files#diff-cbad8a0f4ee75b07aa33761be03e84f3d1196863f60e6fbe01f329c831f23211L84)
- but using only `public` and not `_builtin` post types for setting the defaults in the setting screen: [here](https://github.com/publishpress/PublishPress-Future/pull/58/files#diff-cbad8a0f4ee75b07aa33761be03e84f3d1196863f60e6fbe01f329c831f23211L1387-L1388)

**Comment by stevejburge** [comment]
@contactashish13 Good work, thanks.
