### ISSUE TITLE
Remove timezone tooltip

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Future#592]
I'm not sure we need this timezone tooltip:
![Screenshot 2023-12-11 at 9 17 53 AM](https://github.com/publishpress/PublishPress-Future/assets/3868028/52c109b3-5dfa-4e8b-90ce-fcbbfa859809)

**Comment by andergmartins** [comment]
@stevejburge This is coming from the WP component. I think I can force hide it using CSS, and I see your point for the timezones specified as the offset. Maybe for timezones like "Bogota" it make sense to keep the tooltip since it shows more details?

![image](https://github.com/publishpress/PublishPress-Future/assets/407131/77a75f36-4863-4c51-80a0-bf173b6d11d7)

**Comment by stevejburge** [comment]
Ah, got it, thanks. Let's not worry too much about this
