### ISSUE TITLE
Should users be able to select a label under "Manually enabled via Future Actions box"

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Future#822]
The default is always "Trigger workflow"

![Screenshot 2024-06-26 at 5 23 59 PM](https://github.com/publishpress/PublishPress-Future/assets/3868028/e1a2c742-515e-4b94-8543-ffcdfb850083)

**Comment by andergmartins** [comment]
@stevejburge do you mean we should not only provide a text field for choosing the action label, but display each workflow, or trigger, as a different option in the Future Box, instead of the Trigger Workflow action?

Considering we have a workflow with two triggers (not useful right now, but will be in the future when we have conditional steps), each one with a custom label:


![Image](https://github.com/user-attachments/assets/a46c707e-7ae5-43f9-b231-24fa2721b942)

![Image](https://github.com/user-attachments/assets/4d97401c-67c5-4c6a-b39b-095b30484031)

And a possible second workflow, with the same trigger (but no custom label, so it displays the workflow name)


![Image](https://github.com/user-attachments/assets/27a33297-6ce2-411d-b6c4-aa39f1711e5a)


We should see something like:


![Image](https://github.com/user-attachments/assets/35826fa3-a6ce-485f-820b-5fa78d795f11)

So we display individual actions, instead of a unique "Trigger workflow" action which allows to select the workflows. An advantage of this is that multiple triggers can fire different paths on the same workflow.

**Comment by stevejburge** [comment]
@andergmartins Maybe this is old feedback now. It looks correct now. In older versions, I think it always showed up as "Trigger workflow"

**Comment by andergmartins** [comment]
@stevejburge Ah! Got it, thanks.
