### ISSUE TITLE
Small changes to new step

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Future#909]
- Should be "The field Post is required"
- The first two fields only have one choice. Can we choose those automatically?
![Screenshot 2024-08-21 at 4 20 42 PM](https://github.com/user-attachments/assets/769e244c-4c8e-4130-8d4d-6019b4dad453)

**Comment by andergmartins** [comment]
@stevejburge I'm afraid we can't fill those fields automatically.

The field itself evaluates the available options for each field. The problem is that for optimization purposes (and how React works) the field does not exist in the runtime until it is displayed.

We could probably find a way to implement that, but I would not call that a minor issue.

**Comment by stevejburge** [comment]
OK, no worries. We'll postpone this then.

**Comment by andergmartins** [comment]
Second request moved to #912
